[package]
name = "firmware_bruteforcer"
version = "0.1.1"
edition = "2026"

[[bin]]
name = "xor_firmware_bruteforcer"
path = "filesystem-xor-bruteforce.rs"

[[bin]]
name = "rc4_finder"
path = "rc4_finder.rs"

[dependencies]
num_cpus = "1.16"
